#!/usr/bin/env python3
"""Auto-generate title-translations-<module>.json by stripping 'MII PR <Mod> '
prefix from upstream parent titles. Existing entries in the target file are
preserved (manual curation wins)."""
import json, re, sys
from pathlib import Path

MODULES = {
    "mtb":   ("MTB",   "de.medizininformatikinitiative.kerndatensatz.mtb",   "2026.0.1"),
    "patho": ("Patho", "de.medizininformatikinitiative.kerndatensatz.patho", "2026.0.1"),
    "icu":   ("ICU",   "de.medizininformatikinitiative.kerndatensatz.icu",   "2026.0.2"),
}
CACHE = Path.home() / ".fhir/packages"
DEST = Path(__file__).resolve().parent

# English clinical term hints — when these remain after prefix-strip, the entry
# needs manual DE translation, not just the auto-stripped EN-as-DE pass-through.
EN_HINTS = re.compile(
    r"\b(Immuno|Histo|Score|Disease|Function|Treatment|Intensity|Bundle|"
    r"Composition|Conclusion|Grouper|Finding|Image|Anamnese|Microscopic|"
    r"Macroscopic|Service|Request|Specimen|Cells|Counted|Reference|Body|"
    r"Site|Type|Code|Procedure|Report|Method|Indication|Identifier|Status|"
    r"History|Present|Illness|Department|Family|Subject|Adverse|Effect|"
    r"Encounter|Patient|Provider|Location|Sample|Cause|Result|Observation|"
    r"Performer|Reason|Authority|Concept|Question)",
    re.IGNORECASE,
)

def needs_review(de_text):
    """German hint: contains umlauts or known German words. Otherwise flag."""
    if re.search(r"[äöüÄÖÜß]", de_text):
        return False
    if re.search(r"\b(der|die|das|und|für|nach|mit|von|zur|bei|als|im|am|"
                  r"Untersuchung|Befund|Probe|Diagnose|Behandlung|Anforderung)\b",
                  de_text):
        return False
    if EN_HINTS.search(de_text):
        return True
    return False

def repo_path_for(module):
    return DEST / f"title-translations-{module}.json"

def load_existing(path):
    if not path.exists():
        return {}, None
    with open(path) as f:
        data = json.load(f)
    doc = data.pop("_doc", None) if isinstance(data, dict) else None
    return data, doc

def process(module):
    mod_label, pkg, ver = MODULES[module]
    pkg_dir = CACHE / f"{pkg}#{ver}" / "package"
    out_path = repo_path_for(module)
    existing, doc = load_existing(out_path)

    added, skipped, review = 0, 0, []
    prefix_re = re.compile(rf"^MII\s+PR\s+{mod_label}\s+", re.IGNORECASE)

    for f in sorted(pkg_dir.iterdir()):
        if not f.name.endswith(".json"): continue
        if not f.name.startswith("StructureDefinition-"): continue
        with open(f) as fh: sd = json.load(fh)
        if sd.get("resourceType") != "StructureDefinition": continue
        if sd.get("kind") != "resource": continue
        if sd.get("derivation") != "constraint": continue
        name = sd.get("name", "")
        title = sd.get("title", "")
        if not name or not title:
            continue
        if name in existing:
            # Manual curation already exists — don't overwrite
            skipped += 1
            continue
        # Strip prefix
        stripped = prefix_re.sub("", title).strip()
        if not stripped:
            stripped = title
        # Heuristic: DE = stripped, EN = stripped (since they're the same now)
        existing[name] = {"de-DE": stripped, "en-US": stripped}
        added += 1
        if needs_review(stripped):
            review.append((name, stripped))

    doc = doc or (
        f"Auto-stripped DE/EN titles for the '{module}' module — generated by "
        f"scripts/auto-strip-titles.py with the 'MII PR {mod_label} ' prefix "
        f"removed from upstream parent titles. Manual edits are preserved on "
        f"re-runs (existing keys are not overwritten). Entries flagged for "
        f"review still contain English-only text after stripping."
    )
    out = {"_doc": doc, **existing}
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"  {module}: +{added} added, {skipped} kept curated, {len(review)} flagged for review")
    for name, title in review[:8]:
        print(f"    REVIEW: {name}  →  '{title}'")
    if len(review) > 8:
        print(f"    ... +{len(review)-8} more")

if __name__ == "__main__":
    for m in sys.argv[1:] or list(MODULES):
        process(m)
